title: gekas145
author:
  name: GitHub User
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Some cool description.

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
# remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic
  


